version: '3.8'

services:
  database:
    container_name: database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_pm
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    networks:
      - private
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: php
    networks:
      - private
      - public
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_pm
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    networks:
      - private
      - public
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_pm
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

networks:
  private:
  public: